#!/usr/bin/env bash

set -uo pipefail
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

source /etc/lsb-release

# check that we are root
if [[ $EUID -ne 0 ]]; then
  echo "Sorry, this script must be run as root"
  exit 1
fi

# remove old docker versions
apt-get remove -y --purge docker docker-engine docker.io containerd runc

# Set up Docker repo
apt-get install -y ca-certificates curl gnupg lsb-release

# Add GPG key
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

# Install docker
apt-get update -y
apt-get install -y docker-ce docker-ce-cli containerd.io

# Run hello-world test
docker run hello-world

# Install docker-compose
sudo curl -sSL "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

# Install completions
if [[ $(grep "^$USER": /etc/passwd | grep -Eo ':([^:]*)$' | tr -d ':') == "/bin/bash" ]]; then
	curl -L https://raw.githubusercontent.com/docker/compose/1.29.2/contrib/completion/bash/docker-compose -o /usr/local/etc/bash_completion.d/docker-compose
fi

# ZSH Completions
if [[ $(grep "^$USER": /etc/passwd | grep -Eo ':([^:]*)$' | tr -d ':') == "/bin/zsh" ]]; then
	mkdir -p ~/.zsh/completion
	curl -L https://raw.githubusercontent.com/docker/compose/1.29.2/contrib/completion/zsh/_docker-compose -o ~/.zsh/completion/_docker-compose
	echo "fpath=(/home/$USER/.zsh/completion $fpath)" >> /home/"$USER"/.zshrc
fi

exit 0
