#!/usr/bin/env bash

set -e

# Must be root to do this

if [[ $EUID -ne 0 ]]; then 
    echo "Sorry, you must run this script as root!"
    exit 1
fi

rm /etc/ssh/ssh_host*key*

# Create new keys

ssh-keygen -t ed25519 -N "" -o -a 100 -f /etc/ssh/ssh_host_ed25519_key > /dev/null 2>&1 &
ssh-keygen -t rsa -b 4096 -N "" -o -a 100 -f /etc/ssh/ssh_host_rsa_key > /dev/null 2>&1 &