#!/usr/bin/env bash
set -uo pipefail
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

# Short link https://bit.ly/3CFjr7J
# Download and run this script with sudo bash -c "bash <(curl -sSL https://bit.ly/3CFjr7J)"

# Run this script after you have fully installed your distro
# You must use systemd as your init system

# check that we are root
if [[ $EUID -ne 0 ]]; then
  echo "Sorry, this script must be run as root"
  exit 1
fi

# set hostname
#read -p "Enter new hostname: " newHostname
newHostname=$(dialog --stdout --inputbox "Enter Hostname" 0 0) || exit 1
clear
: ${hostname:?"Hostname cannot be empty}

echo "Setting hostname..."
sed -i "s/$HOSTNAME/$newHostname/g" /etc/hosts
sed -i "s/$HOSTNAME/$newHostname/g" /etc/hostname
hostnamectl set-hostname $newHostname

# Change root password
#read -p "Change your password now: " newPassword
newPassword=$(dialog --stdout --inputbox "Enter administrator password" 0 0) || exit 1
clear 
: ${password:?"Password cannot be empty"}

newPassword2=$(dialog --stdout --passwordbox "Enter administrator password again" 0 0) || exit 1
clear
[[ "$newPassword" == "$newPassword2"  ]] || ( echo "Passwords did not match"; exit 1; )

echo "$USER:$newPassword" | chpasswd --root /
echo "root:$newPassword" | chpasswd --root /

# set new machine ID
# Systemd only, opinionated
echo "Setting new machine ID..."
rm /etc/machine-id
systemd-machine-id-setup

# Create new SSH Keys
echo "Creating new SSH host keys..."
rm -f /etc/ssh/ssh_host*key*
ssh-keygen -t rsa -b 4096 -o -a 100 -N "" -f /etc/ssh/ssh_host_rsa_key
ssh-keygen -t ed25519 -o -a 100 -N "" -f /etc/ssh/ssh_host_ed25519_key

# Secure SSH configurations
echo "Updating OpenSSH configuration"
# sshd_config
curl -sSLo sshd_config https://bit.ly/3oRAYEP && install -m 0644 sshd_config /etc/ssh/sshd_config

# ssh_config
curl -sSLo ssh_config https://bit.ly/3kVlu1g && install -m 0644 ssh_config /etc/ssh/ssh_config

# rsync.d log destination
echo "Adding log destination to rsyslog"
echo "*.* @logserver:514" > /etc/rsyslog.d/100-logserver.conf

echo "Restarting services with new configurations"
systemctl enable --now rsyslog ssh

echo "Restarting shell to load new values..."
sleep 5
exec $SHELL

exit 0
