#!/usr/bin/env bash
set -e

# Short link https://bit.ly/3kWAKuM
# Download and run this script with sudo bash -c "bash <(curl -sSL https://bit.ly/3kWAKuM)"

# Run this script after you have fully installed your distro
# You must use systemd as your init system

# check that we are root
if [[ $EUID -ne 0 ]]; then
  echo "Sorry, this script must be run as root"
  exit 1
fi

# set hostname
read -p "Enter new hostname: " newHostname
echo "Setting hostname..."
sed -i "s/$HOSTNAME/$newHostname/g" /etc/hosts
sed -i "s/$HOSTNAME/$newHostname/g" /etc/hostname
hostnamectl set-hostname $newHostname

# set new machine ID
# Systemd only, opinionated
echo "Setting new machine ID..."
rm /etc/machine-id
systemd-machine-id-setup

# Create new SSH Keys
echo "Creating new SSH host keys..."
rm -f /etc/ssh/ssh_host*key*
ssh-keygen -t rsa -b 4096 -o -a 100 -N "" -f /etc/ssh/ssh_host_rsa_key
ssh-keygen -t ed25519 -o -a 100 -N "" -f /etc/ssh/ssh_host_ed25519_key

# Secure SSH configurations
echo "Updating OpenSSH configuration"
# sshd_config
curl -sSLO sshd_config https://bit.ly/3oRAYEP && install -m 0644 sshd_config /etc/ssh/sshd_config

# ssh_config
curl -sSLO ssh_config https://bit.ly/3kVlu1g && install -m 0644 ssh_config /etc/ssh/ssh_config

# rsync.d log destination
echo "Adding log destination to rsyslog"
echo "*.* @logserver:514" > /etc/rsyslog.d/100-logserver.conf

echo "Restarting services with new configurations"
systemctl restart rsyslogd sshd


echo "Restarting shell to load new values..."
sleep 5
exec $SHELL

exit 0
